### ISSUE TITLE
FG02 - Modifier les information de la salle de spectacle

### ISSUE THREAD

**Issue by slush450** [gti525/e18-gestion-spectacles#2]
En tant qu'administrateur du gestionnaire de salle, je dois pouvoir modifier les information de la salle de spectacle

**Comment by ygotame** [comment]
Cette tache est fait. On attend la validation de l'équipe pour finaliser. 
Le travail est fait dans le branch : https://github.com/gti525/e18-gestion-spectacles/tree/dev-dockercompose

**Comment by ygotame** [comment]
Le test fonctionne bien.
On attend que le schema API  que le site vente des billets pour intergrer dans notre système

**Comment by ygotame** [comment]
Voir #9  pour la suite.
