### ISSUE TITLE
FG03 - Publier de nouveaux spectacles sur le site de vente de billets de spectacles

### ISSUE THREAD

**Issue by slush450** [gti525/e18-gestion-spectacles#3]
En tant qu'administrateur du gestionnaire de salle, je dois pouvoir publier de nouveaux spectacles sur le site de vente de billets de spectacles

**Comment by ygotame** [comment]
Cette tâche est aussi fini. En attente la validation de l'équipe
https://github.com/gti525/e18-gestion-spectacles/tree/dev-dockercompose

**Comment by ygotame** [comment]
Le test fonctionne bien.
On attend que le schema API  que le site vente des billets pour intergrer dans notre système
