### ISSUE TITLE
FG04  - Visualiser la liste des spectacles à venir dans la salle de spectacle

### ISSUE THREAD

**Issue by slush450** [gti525/e18-gestion-spectacles#4]
En tant qu'administrateur du gestionnaire de salle, je dois pouvoir visualiser la liste des spectacles à venir dans la salle de spectacle

**Comment by ygotame** [comment]
Cette tâche est en cours en prenant en considération avec le nouveau changement ( qui est d'utiliser les api de site de vente )

**Comment by ygotame** [comment]
Cela est fonctionnel avec le nouveau code en utilisant les API de site-de-vente.
