### ISSUE TITLE
FG06 - Production d'un rapport de vente pour chaque spectale

### ISSUE THREAD

**Issue by slush450** [gti525/e18-gestion-spectacles#6]
En tant que gestionnaire de salle, je dois permettre la production d'un rapport de vente pour chaque spectable

**Comment by ygotame** [comment]
Pour le sprint 4, je vais prendre en charge cette partie en intégrant avec les autres fonctionnalités. 

Je ferai seulement cette tâche pour le sprint 4, car je dois finaliser avec les autres fonctionnalités et aussi, j'aurai moins de temps car je suis en mission internationale avec mon club étudiant durant une bonne partie du sprint 4.

**Comment by ygotame** [comment]
Le rapport est en cours mais je dois modifier pour adapter pour connecter sur les API-Vente pour gérer les spectacles.

**Comment by ygotame** [comment]
Le serveur API du site-vente 1 et 2 sont accesibles, ils ne sont pas fonctionnels à 100. Donc, il est très difficile pour moi de tester leur API.

J'ai tout de même créer le code en basant sur le doc du swagger. 

Pour tout tester, il faudra que les de ventes rendent leur API 100% fonctionnels afin que je puisse afficher les informaitons sur le rapport.

Sinon, de mon cote, le code est pret pour tester le tout.

**Comment by ygotame** [comment]
PR #18  a tout les modifications pour produire le rapport
