### ISSUE TITLE
FG07 Pouvoir consulter un rapport d'assistance ou de vente pour chaque spectacle

### ISSUE THREAD

**Issue by slush450** [gti525/e18-gestion-spectacles#7]
En tant qu'administrateur du gestionnaire de salle, je dois pouvoir consulter un rapport d'assistance ou de vente pour chaque spectacle

**Comment by ygotame** [comment]
à cause des imprévus et changements, cette tâches sera pour le dernier sprint soit le 5.

**Comment by ygotame** [comment]
Le gabarit est fait et foncitonnel. Voir #8  pour la suite.
