### ISSUE TITLE
FG08 Consulter un tableau de bord contenant les données du rapport d'assistance et de vente pour un spectacle donné

### ISSUE THREAD

**Issue by slush450** [gti525/e18-gestion-spectacles#8]
En tant qu'administrateur du gestionnaire de salle, je dois pouvoir consulter un tableau de bord contenant les données du rapport d'assistance et de vente pour un spectacle donné

**Comment by ygotame** [comment]
Cette tâche dépend #FG07. Cela sera fait aussi au sprint 5.

**Comment by ygotame** [comment]
Rapport de vente est déjà fait.
J'attends les informations du Gestion Billets pour créer le rapport d'assistance.
