### ISSUE TITLE
FG09 (Début de FG02, Création de FG09) Modifier les information de la salle de spectacle

### ISSUE THREAD

**Issue by slush450** [gti525/e18-gestion-spectacles#9]

**Comment by ygotame** [comment]
Projet est démarré. Fonctionnement du formulaire est en cours. On va valider le prototypage crée pour finaliser le formulaire. 

Cette tâches est en cours et va être finaliser durant le sprint 3.

**Comment by ygotame** [comment]
La tâche était finaliser. Mais on devait recommencer le travail car il faut travialler avec les API call de site-vente pour gérer les spectacles

**Comment by ygotame** [comment]
Cette tâche est possible aussi. Mais, comme je ne peux pas encore faire des post sur les API de vente. Cette tâche est encore en attente à cause des site-ventes ne sont pas renu leur API 100% fonctionnels.
